---
title: "Gaming Company Stock Prices"
author: "Cormac Nolan"
date: "6 February 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, message=FALSE, warning = FALSE}
library(dplyr)
library(ggplot2)
library(purrr)
library(quantmod)
library(tsibble)
library(feasts)
```

## Import and Setup

```{r functions}
add_stocks <- function(df, ticker_var, start_date, end_date, data_source = "yahoo") {
  ticker_q = dplyr::enquo(ticker_var)
  mutate(df, 
         stocks = map(!! ticker_q, 
                      function(x, y, z) getSymbols(x, src = data_source, 
                                                   from = y, to = z, 
                                                   auto.assign = FALSE),
                      start_date, end_date))
}

extract_xts <- function(xts_obj, ticker_name, metric) {
  xts_column = paste0(ticker_name, ".", metric)
  result <- 
    xts_obj[ , xts_column] %>% 
    as.data.frame() %>% 
    tibble::rownames_to_column(var = "stock_date") %>% 
    as_tibble() %>% 
    mutate(stock_date = as.Date(stock_date))
  
  result
}

remove_pattern_from_colnames <- function(df, pattern) {
  colnames(df) = stringr::str_replace(colnames(df), pattern, "")
  df
}
```

Retrieve the stocks...
```{r, cache = TRUE}
gaming_stock_tickers <- c("EA", "ATVI", "NTDOY", "NVDA")
gaming_and_casino_stock_tickers <- c("MGM", "LVS", "MLCO", "WYNN")
tech_stock_tickers <- c("MSFT", "AAPL", "GOOGL", "FB", "INTC", "CSCO", "TSM", "ORCL", "ADBE", "IBM")

analysis_dates <- list(start = as.Date("2016-01-01"), end = as.Date(Sys.Date()))


gaming_stocks_raw <-
  tibble(tickers = gaming_stock_tickers) %>% 
  add_stocks(tickers, analysis_dates$start, analysis_dates$end)

casino_stocks_raw <-
  tibble(tickers = gaming_and_casino_stock_tickers) %>% 
  add_stocks(tickers, analysis_dates$start, analysis_dates$end)

tech_stocks_raw <-
  tibble(tickers = tech_stock_tickers) %>% 
  add_stocks(tickers, analysis_dates$start, analysis_dates$end)
```

## Transform & Clean
Extract the closing stock price as a data frame.
```{r}

gaming_stocks <-
  gaming_stocks_raw %>% 
  mutate(closing = map2(stocks, tickers, 
                        function(stk, tck, var_name) extract_xts(stk, tck, var_name), "Close")) %>% 
  mutate(closing = map2(closing, tickers, 
                        function(cls, tck) remove_pattern_from_colnames(cls, paste0(tck, "\\."))))

tech_stocks <-
  tech_stocks_raw %>% 
  mutate(closing = map2(stocks, tickers, 
                        function(stk, tck, var_name) extract_xts(stk, tck, var_name), "Close")) %>% 
  mutate(closing = map2(closing, tickers, 
                        function(cls, tck) remove_pattern_from_colnames(cls, paste0(tck, "\\."))))

casino_stocks <-
  casino_stocks_raw %>% 
  mutate(closing = map2(stocks, tickers, 
                        function(stk, tck, var_name) extract_xts(stk, tck, var_name), "Close")) %>% 
  mutate(closing = map2(closing, tickers, 
                        function(cls, tck) remove_pattern_from_colnames(cls, paste0(tck, "\\."))))

map2(tech_stocks$closing, tech_stocks$tickers, 
     function(x, y) qplot(stock_date, Close,  data = x, geom = "line", main = y))
  
```

## Analysis
### Normalise Gaming Stocks
Normalise each stock agains the max price of the stock over the period.
```{r}
gaming_stocks_normalised <-
  gaming_stocks %>% 
  mutate(closing_normalised = map(closing, function(df) { df$Close <- df$Close / max(df$Close) ; df })) %>% 
  mutate(closing_normalised = map2(closing_normalised, tickers, function(x, y) mutate(x, ticker = y)))

gaming_stocks_df <-
  dplyr::bind_rows(gaming_stocks_normalised$closing_normalised) %>% 
  spread(ticker, Close) %>% 
  mutate(stock_mean = pmap_dbl(select(., -stock_date), .f = ~mean(c(...)))) %>% 
  select(stock_date, stock_mean)

gaming_stocks_normalised %>% 
  mutate(closing_normalised = map(closing_normalised, 
                                  function(x, y) left_join(x, y, by = c("stock_date")), 
                                  gaming_stocks_df)) %>% 
  mutate(correlation_to_mean = map_dbl(closing_normalised, function(x) cor(x$Close, x$stock_mean)))


```


```{r}
gaming_stocks_normalised %>% 
  select(closing_normalised) %>% 
  pull() %>% 
  bind_rows() %>% 
  ggplot(aes(stock_date, Close, colour = ticker)) +
  geom_smooth(se = FALSE, span = 0.2) +
  geom_line(alpha = 0.3)
```

### Normalise Tech Stocks
```{r}
tech_stocks_normalised <-
  tech_stocks %>%
  mutate(closing_normalised = map(closing, 
                                  function(df) { df$Close <- df$Close / max(df$Close) ; df })) %>% 
  mutate(closing_normalised = map2(closing_normalised, tickers, 
                                   function(x, y) mutate(x, ticker = y)))

tech_stocks_normalised %>% 
  select(-stocks, -closing) %>% 
  unnest %>%
  group_by(stock_date) %>% 
  summarise(mean_close = mean(Close)) %>% 
  ggplot(aes(stock_date, mean_close)) +
  geom_line()

tech_stocks_mean <-
  tech_stocks_normalised %>% 
  select(-stocks, -closing) %>% 
  unnest %>% 
  group_by(stock_date) %>% 
  summarise(mean_close = mean(Close))
```

### Normalise Casino Stocks
```{r}

casino_stocks_raw

casino_stocks_normalised <-
  casino_stocks %>%
  mutate(closing_normalised = map(closing, 
                                  function(df) { df$Close <- df$Close / max(df$Close) ; df })) %>% 
  mutate(closing_normalised = map2(closing_normalised, tickers, 
                                   function(x, y) mutate(x, ticker = y)))

casino_stocks_normalised %>% 
  select(-stocks, -closing) %>% 
  unnest %>%
  group_by(stock_date) %>% 
  summarise(mean_close = mean(Close)) %>% 
  ggplot(aes(stock_date, mean_close)) +
  geom_line()

casino_stocks_mean <-
  casino_stocks_normalised %>% 
  select(-stocks, -closing) %>% 
  unnest %>% 
  group_by(stock_date) %>% 
  summarise(mean_close = mean(Close))
```

### Normalise Games to Tech
```{r}
gaming_stocks_normalised$tech_mean <- rep(list(tech_stocks_mean), 4)

p_game_v_tech <- 
  gaming_stocks_normalised %>% 
  mutate(gaming_normalised_to_tech = map2(closing_normalised, tech_mean, 
                                          function(x, y) { (x$Close / y$mean_close) })) %>%
  select(tickers, gaming_normalised_to_tech, closing_normalised, tech_mean) %>% 
  unnest() %>% 
  ggplot(aes(stock_date, gaming_normalised_to_tech, colour = tickers)) +
  geom_line(alpha = 0.3) +
  geom_smooth(se = FALSE, span = 0.2) +
  labs(title = "Gaming Company Stocks Normalised to US Tech",
       subtitle = "Closing stock value divided by closing mean of 8 US tech firms - 1.0 means they performed equally as well relative to each stock's peak",
       y = "Normalised Stock Performance") +
  blorg::blog_theme +
  theme(legend.position = "none") +
  scale_colour_manual(values = blorg::blog_palette[c(1,2,4,7)]) +
  scale_y_continuous(breaks = c(0.25, 0.5, 0.75, 1.0, 1.25, 1.5), limits = c(0.0, 1.5))
  
```

### Normalise Games to Casinos
```{r}
gaming_stocks_normalised$casino_mean <- rep(list(casino_stocks_mean), 4)

p_game_v_casino <-
  gaming_stocks_normalised %>% 
  mutate(gaming_normalised_to_casino = map2(closing_normalised, casino_mean, 
                                          function(x, y) { (x$Close / y$mean_close) })) %>%
  select(tickers, gaming_normalised_to_casino, closing_normalised, casino_mean) %>% 
  unnest() %>% 
  ggplot(aes(stock_date, gaming_normalised_to_casino, colour = tickers)) +
  geom_line(alpha = 0.3) +
  geom_smooth(se = FALSE, span = 0.2) +
  labs(title = "Gaming Company Stocks Normalised to Casino Stocks",
       subtitle = "Closing stock value divided by closing mean of 4 casino  firms - 1.0 means they performed equally as well relative to each stock's peak",
       y = "Normalised Stock Performance") +
  blorg::blog_theme +
  theme(axis.title.y = element_blank()) +
  scale_colour_manual(values = blorg::blog_palette[c(1,2,4,7)]) +
  scale_y_continuous(breaks = c(0.25, 0.5, 0.75, 1.0, 1.25, 1.5), limits = c(0.0, 1.5))
  
gridExtra::grid.arrange(p_game_v_tech, p_game_v_casino, ncol = 2)
```

```{r}
gaming_stocks_normalised %>% 
  mutate(gaming_normalised_to_casino = map2(closing_normalised, casino_mean, 
                                          function(x, y) { (x$Close / y$mean_close) })) %>%
  select(tickers, gaming_normalised_to_casino, closing_normalised, casino_mean) %>% 
  unnest() %>% 
  ggplot(aes(stock_date, mean_close)) +
  geom_line(alpha = 0.3) +
  geom_smooth(se = FALSE, span = 0.2) +
  geom_line(aes(stock_date, Close, colour = ticker), inherit.aes = FALSE)
```


